name: flutter_kanada_app
description: "A new Flutter Kanada App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/kanada-dailyapp.webp"