name: flutter_kannada_app
description: "A new Flutter Kannada App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/kanada-dailyapp.webp"